### ISSUE TITLE
你好，最近在用的时候发现可能是个bug。

### ISSUE THREAD

**Issue by jijingtaifeng** [linheimx/LChart#9]
错误提示：
       java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
       at com.linheimx.app.library.render.LineRender.onChartSizeChanged(LineRender.java:60)
       at com.linheimx.app.library.charts.LineChart.onSizeChanged(LineChart.java:224)
        at android.view.View.sizeChange(View.java:17187)
        at android.view.View.setFrame(View.java:17149)
         at android.view.View.layout(View.java:17040)

错误定位是在 LineRender.java类中的

 public void onChartSizeChanged(int w, int h) {
            _drawBitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
            softwareCanvas.setBitmap(_drawBitmap);
    }
原因大概是 传入给Bitmap参数前，进行下width、height的判断，必须大于0。
这个问题一般不会出现，只是我的布局比较特殊所以会出现错误。

修改后
  public void onChartSizeChanged(int w, int h) {
        if (w>0&&h>0){
            _drawBitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
            softwareCanvas.setBitmap(_drawBitmap);
        }
    }

以上意见仅供参考！

**Comment by linheimx** [comment]
嗯，今天才看到，这么处理是可以的。
你可以pull request上来，我直接合并上来。这样你也是贡献者啦～

**Comment by jijingtaifeng** [comment]
那不用了哈，只是一个小的判断而已。

**Comment by linheimx** [comment]
那我下午把它加上 =w=

**Comment by linheimx** [comment]
已加入，版本更新至 1.2.4
